/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamIdRouteImport } from './routes/exam.$id'
import { Route as ExamIdReviewRouteImport } from './routes/exam.$id.review'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdRoute = ExamIdRouteImport.update({
  id: '/exam/$id',
  path: '/exam/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIdReviewRoute = ExamIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ExamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/exam/$id': typeof ExamIdRouteWithChildren
  '/exam/$id/review': typeof ExamIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/exam/$id': typeof ExamIdRouteWithChildren
  '/exam/$id/review': typeof ExamIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/exam/$id': typeof ExamIdRouteWithChildren
  '/exam/$id/review': typeof ExamIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirmation'
    | '/login'
    | '/exam/$id'
    | '/exam/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/confirmation'
    | '/login'
    | '/exam/$id'
    | '/exam/$id/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirmation'
    | '/login'
    | '/exam/$id'
    | '/exam/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConfirmationRoute: typeof ConfirmationRoute
  LoginRoute: typeof LoginRoute
  ExamIdRoute: typeof ExamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$id': {
      id: '/exam/$id'
      path: '/exam/$id'
      fullPath: '/exam/$id'
      preLoaderRoute: typeof ExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$id/review': {
      id: '/exam/$id/review'
      path: '/review'
      fullPath: '/exam/$id/review'
      preLoaderRoute: typeof ExamIdReviewRouteImport
      parentRoute: typeof ExamIdRoute
    }
  }
}

interface ExamIdRouteChildren {
  ExamIdReviewRoute: typeof ExamIdReviewRoute
}

const ExamIdRouteChildren: ExamIdRouteChildren = {
  ExamIdReviewRoute: ExamIdReviewRoute,
}

const ExamIdRouteWithChildren =
  ExamIdRoute._addFileChildren(ExamIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConfirmationRoute: ConfirmationRoute,
  LoginRoute: LoginRoute,
  ExamIdRoute: ExamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
